FROM public.ecr.aws/lambda/python:3.11

# Copy requirements and install them
COPY requirements.txt .
RUN pip3 install --upgrade pip && pip3 install -r requirements.txt

# Copy function code
COPY . .

# Command Lambda will call
CMD ["lambda_function.lambda_handler"]
